services:
  # A Docker web service
  - type: web
    name: voiceai
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn final:app --host 0.0.0.0 --port $PORT
